CREATE TABLE Booking(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  CustomerId INT NOT NULL,
  TimeslotId INT NOT NULL,
  Textmessage VARCHAR(1000)

);

CREATE TABLE Timeslot(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  EmployeeId INT NOT NULL,
  BookingDate DATE NOT NULL,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL
);

CREATE TABLE Customer(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  SocialSecurityNumber BIGINT,
  FirstName VARCHAR(64),
  LastName VARCHAR(64),
  Email VARCHAR(64),
  PhoneNumber VARCHAR(64)
);

CREATE TABLE Employee(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(64),
  FirstName VARCHAR(64),
  LastName VARCHAR(64),
  Email VARCHAR(64),
  PhoneNumber VARCHAR(64)
);

--CREATE TABLE CONTENT(
--  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
--  SUBJECTS VARCHAR(64)
--  );
--

--CREATE
--TABLE SUBJECTS(
-- BookingId INT,
-- ContentId INT
--  );


CREATE TABLE SUBJECT(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  subject VARCHAR(64)
  );


CREATE TABLE BOOKINGREQUEST(
 Id BIGINT AUTO_INCREMENT PRIMARY KEY,
 CustomerId INT
  );

  CREATE TABLE CONTENT(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    BookingrequestID int,
    SUBJECTSID int
    );

ALTER TABLE Booking ADD FOREIGN KEY (TimeslotId) REFERENCES Timeslot(Id);
ALTER TABLE Booking ADD FOREIGN KEY (CustomerId) REFERENCES Customer(Id);
ALTER TABLE Timeslot ADD FOREIGN KEY (EmployeeId) REFERENCES Employee(Id);
ALTER TABLE BOOKINGREQUEST ADD FOREIGN KEY (CustomerId) REFERENCES Customer(Id);
ALTER TABLE CONTENT ADD FOREIGN KEY (BookingrequestID) REFERENCES BOOKINGREQUEST(Id);
ALTER TABLE CONTENT ADD FOREIGN KEY (SUBJECTSID) REFERENCES subject(Id);
--ALTER TABLE SUBJECTS ADD FOREIGN KEY (BookingId) REFERENCES Booking(Id);
--ALTER TABLE SUBJECTS ADD FOREIGN KEY (ContentId) REFERENCES CONTENT(Id);